travis:
  secure:
    BINSTAR_TOKEN: 0oJ8/9VUOajyQq+51+fPLiz4rBYQyKjRvvYV1WjyKfQvP8W+5RAJIjjR+05GKTiCuN13IuLFcnqgNeC+NNdalsximbTR5VJte2djaOgO72niiMHbh6qr8vb4hB8NE7mx/rFZuDz15JNox9Sr2d7WyHG3VyL2FY0XJ/IH5GeYUGVTH2zkuAnOTwaXykti5bWbohjXfqSiSCApdOomkaGvSgDXMINgqAdG0+yYwmqH1XyIF2BVJycCb8nlXyTLD9aM2Ce9In5fBm2GwNoKHCr9iof5vR+BLcNrhJnSPSnnQyJgb6a2LRNAW6DgSN58/ne7RPWdhbHP0/lNkJn1S3LREV9sCQMYVSv01wqxJuT3eTrQxhBb6TqgKUiyFIHBaCgLXUBz2RHTlZxsRWQOIsR0Zq6oHybMtirvMlpkwoM0ex8EnMpyNbzEVTSmD+/2JYdcOzXxutA0QZGPkIEjCxRauyFiJE3SgZGszfL5Tugq0LpVrl+a9CTb+nZtOxuFk8Xt6jWPsq25GtPVeuhYOjcdCX8xBQDnf0eVKekqXbNzqS/1ngPxatedptT7NuSgNFVlRnNwm0ty7YYXz+nrudW/AiESXYbknk9dj3D0xethnUYeYOkjvIowekmf57KfyRB2HnyoJfcivZ4yCxRcx2BDzXWmDkzd46r0ryEailXO0Wg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
